version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: echo "Add your test command here"
      - run:
          name: Build
          command: npm run heroku-postbuild
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Render Deploy Hook
          command: curl -X POST https://api.render.com/deploy/srv-cpknlsa0si5c73cu7khg?key=8MNnmE77AfY
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
